### ISSUE TITLE
Frank doc generates a lot of WARN messages for default interface methods

### ISSUE THREAD

**Issue by evandongen** [frankframework/frank-doc#243]
While checking the build log for a failed frankframework build, I noticed that there are ~150 warn messages in the log like the following:
```
10:19:57,018 WARN  FrankMethodDocletBase.searchExcludingImplementedInterfaces():99[] Class org.frankframework.pipes.Samba2Pipe inherits method setRealm, but no annotations or JavaDocs are known because the overridden method is not public.
```
This method is defined as `default void setRealm(String realm)` in an interface class. 

In the frank doc it seems that this should not be logged because this is a default method in an interface: https://github.com/frankframework/frank-doc/blob/master/frank-doc-doclet/src/main/java/org/frankframework/frankdoc/wrapper/FrankMethodDocletBase.java#L91

Is this check working correctly? 

While checking this, please make `Attribute [xxx.xxx] lacks description` info log instead of warn, this is in the output hundreds of times as well, but shouldn't be a warning

**Comment by thomaspj10** [comment]
As of the "lack description" logs. These logs exists, so we can see which elements/attributes doesn't have a description and add it. I guess this doesn't help that much because there are plenty without. It might be benefitial to spend a few hours to document as many elements and attributes as possible in an effort to keep the Frank!Doc as complete as possible.

**Comment by thomaspj10** [comment]
I created a quick Python script and there are 212 attributes and 37 elements without any Javadoc. I counted 1875 attributes and 328 elements in total.
